import os
import subprocess
import time
import httpx
import pytest

@pytest.fixture(scope="module", autouse=True)
def docker_cluster():
    deploy_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../deploy"))
    print("Bringing down existing cluster...")
    subprocess.run(["docker", "compose", "down", "-v"], cwd=deploy_dir)

    env_path = os.path.join(deploy_dir, ".env")
    with open(env_path, "w") as f:
        f.write("AIDAR_ADMIN_TOKENS=test_token\n")
        f.write("AIDAR_WORKER_BOOTSTRAP_SECRET=test_secret\n")
        f.write("AIDAR_INSECURE_MODE=1\n")

    print("Starting cluster...")
    subprocess.run(["docker", "compose", "up", "-d", "--build"], cwd=deploy_dir, check=True)

    print("Waiting for cluster to initialize...")
    max_retries = 30
    for i in range(max_retries):
        time.sleep(1)
        try:
            resp = httpx.get("http://127.0.0.1:8000/api/v1/ping")
            if resp.status_code == 200:
                resp = httpx.get("http://127.0.0.1:8000/api/v1/workers", headers={"Authorization": "Bearer test_token"})
                workers = resp.json()
                active = [w for w in workers if w["status"] == "active"]
                if len(active) >= 2:
                    print(f"Cluster ready with {len(active)} active workers.")
                    break
        except Exception:
            pass
    else:
        subprocess.run(["docker", "compose", "logs"], cwd=deploy_dir)
        subprocess.run(["docker", "compose", "down", "-v"], cwd=deploy_dir)
        raise RuntimeError("Cluster failed to initialize properly in time.")

    yield deploy_dir

    print("Tearing down cluster...")
    subprocess.run(["docker", "compose", "down", "-v"], cwd=deploy_dir)


def test_m14_7_demo_execution(docker_cluster):
    """
    M14.7 END-TO-END AIDAR DEMONSTRATION
    Prove that the provided demo script successfully executes an end-to-end distributed job
    against the physical coordinator API.
    """
    script_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../scripts/m14_demo.py"))
    
    # Run the demo script with default arguments (which target localhost:8000)
    result = subprocess.run(
        ["python", script_path], 
        capture_output=True, 
        text=True
    )
    
    print("DEMO STDOUT:")
    print(result.stdout)
    
    if result.stderr:
        print("DEMO STDERR:")
        print(result.stderr)
        
    assert result.returncode == 0, f"Demo script failed with exit code {result.returncode}"
    
    assert "DEMO SUCCESSFULLY COMPLETED" in result.stdout
    assert "Verified Distributed Execution" in result.stdout
    assert "Discovered and indexed" in result.stdout
    assert "CAS artifact(s) generated by the workloads" in result.stdout
