import os
import subprocess
import time
import httpx
import pytest
from aidars.distributed.models import WorkloadSpec

@pytest.fixture(scope="module", autouse=True)
def docker_cluster():
    deploy_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../deploy"))
    print("Bringing down existing cluster...")
    subprocess.run(["docker", "compose", "down", "-v"], cwd=deploy_dir)

    env_path = os.path.join(deploy_dir, ".env")
    with open(env_path, "w") as f:
        f.write("AIDAR_ADMIN_TOKENS=test_token\n")
        f.write("AIDAR_WORKER_BOOTSTRAP_SECRET=test_secret\n")
        f.write("AIDAR_INSECURE_MODE=1\n")

    print("Starting cluster...")
    subprocess.run(["docker", "compose", "up", "-d", "--build"], cwd=deploy_dir, check=True)

    print("Waiting for cluster to initialize...")
    max_retries = 30
    for i in range(max_retries):
        time.sleep(1)
        try:
            resp = httpx.get("http://127.0.0.1:8000/api/v1/ping")
            if resp.status_code == 200:
                resp = httpx.get("http://127.0.0.1:8000/api/v1/workers", headers={"Authorization": "Bearer test_token"})
                workers = resp.json()
                active = [w for w in workers if w["status"] == "active"]
                if len(active) >= 2:
                    print(f"Cluster ready with {len(active)} active workers.")
                    break
        except Exception:
            pass
    else:
        subprocess.run(["docker", "compose", "logs"], cwd=deploy_dir)
        subprocess.run(["docker", "compose", "down", "-v"], cwd=deploy_dir)
        raise RuntimeError("Cluster failed to initialize properly in time.")

    yield

    print("Tearing down cluster...")
    subprocess.run(["docker", "compose", "down", "-v"], cwd=deploy_dir)

def test_m14_3_true_multi_worker_execution():
    """
    M14.3 TRUE MULTI-WORKER EXECUTION
    Prove that one logical AIDAR job can contain multiple workloads/chunks
    that are actually dispatched to multiple distinct worker instances.
    """
    job_id = f"m14-3-multi-worker-job-{int(time.time())}"
    
    spec1 = WorkloadSpec(
        workload_id=f"{job_id}-chunk-0",
        job_id=job_id,
        task_type="test",
        min_ram_bytes=1024,
        affinity_group_id=job_id,
        affinity_mode="different_worker",
        affinity_hard=True,
        parameters={
            "command": "python -c \"import time; import os; os.makedirs('outputs', exist_ok=True); open('outputs/chunk0.txt', 'w').write('hello from chunk-0'); time.sleep(2); print('chunk-0')\""
        }
    )
    
    spec2 = WorkloadSpec(
        workload_id=f"{job_id}-chunk-1",
        job_id=job_id,
        task_type="test",
        min_ram_bytes=1024,
        affinity_group_id=job_id,
        affinity_mode="different_worker",
        affinity_hard=True,
        parameters={
            "command": "python -c \"import time; time.sleep(2); print('chunk-1')\""
        }
    )

    spec3 = WorkloadSpec(
        workload_id=f"{job_id}-chunk-2",
        job_id=job_id,
        task_type="test",
        min_ram_bytes=1024,
        affinity_group_id=job_id,
        affinity_mode="different_worker",
        affinity_hard=True,
        parameters={
            "command": "python -c \"import time; time.sleep(2); print('chunk-2')\""
        }
    )
    
    headers = {"Authorization": "Bearer test_token"}
    payload = {
        "specs": [
            spec1.model_dump(mode="json"),
            spec2.model_dump(mode="json"),
            spec3.model_dump(mode="json")
        ]
    }
    
    resp = httpx.post("http://127.0.0.1:8000/api/v1/jobs/submit", json=payload, headers=headers)
    assert resp.status_code == 202, f"Failed to submit job: {resp.text}"
    
    max_wait = 30
    for _ in range(max_wait):
        time.sleep(1)
        resp = httpx.get(f"http://127.0.0.1:8000/api/v1/jobs/{job_id}", headers=headers)
        if resp.status_code == 200:
            data = resp.json()
            if data["state"] == "completed":
                break
            elif data["state"] == "failed":
                pytest.fail(f"Job failed unexpectedly: {data}")
    else:
        pytest.fail("Job did not complete within the expected time.")
        
    resp = httpx.get(f"http://127.0.0.1:8000/api/v1/jobs/{job_id}", headers=headers)
    data = resp.json()
    assert data["state"] == "completed"
    
    # Verify that the output artifact generated by chunk-0 survives aggregation
    assert len(data.get("output_asset_hashes", [])) > 0, "Output asset from chunk-0 did not survive aggregation!"
    
    worker_ids = set()
    workload_ids = [spec1.workload_id, spec2.workload_id, spec3.workload_id]
    
    for wid in workload_ids:
        w_resp = httpx.get(f"http://127.0.0.1:8000/api/v1/workloads/{wid}", headers=headers)
        w_data = w_resp.json()
        assert w_data["state"] == "completed"
        
        assert "result" in w_data
        assert w_data["result"]["success"] is True
        
        # Verify stdout survival
        stdout = w_data["result"].get("stdout_snippet", "")
        chunk_num = wid.split("-")[-1]
        assert f"chunk-{chunk_num}" in stdout, f"Stdout snippet missing for chunk-{chunk_num}"
        
        assert "placement" in w_data
        worker_id = w_data["placement"]["selected_worker_id"]
        worker_ids.add(worker_id)
        
    # We expect the chunks to be load balanced across multiple available workers.
    assert len(worker_ids) >= 2, f"Workloads were not distributed across multiple workers. Assigned workers: {worker_ids}"
