#!/usr/bin/env python3
"""
AIDAR M14.7 Capstone Demonstration

Provides a full end-to-end demonstration of the AIDAR platform:
- Cluster health and peer connectivity validation
- Distributed workload placement
- Job lifecycle tracking (Submission -> Aggregation)
- Artifact tracking and generation

Usage:
  python scripts/m14_demo.py [--url http://127.0.0.1:8000] [--token test_token]
"""

import argparse
import json
import os
import sys
import time
from typing import Any, Dict, List
import uuid

try:
    import httpx
except ImportError:
    print("Error: The demo requires the 'httpx' package.")
    print("Install it via: pip install httpx")
    sys.exit(1)


class AIDARDemo:
    def __init__(self, url: str, token: str, timeout: float):
        self.url = url.rstrip("/")
        self.token = token
        self.timeout = timeout
        self.headers = {"Authorization": f"Bearer {self.token}"}
        
    def _print_step(self, step_name: str):
        print(f"\n[{time.strftime('%H:%M:%S')}] \033[1;36m== {step_name} ==\033[0m")
        
    def _print_success(self, msg: str):
        print(f"\033[1;32m[SUCCESS] {msg}\033[0m")

    def _print_error(self, msg: str):
        print(f"\033[1;31m[ERROR] {msg}\033[0m")
        
    def _print_info(self, msg: str):
        print(f"  {msg}")

    def run(self):
        print("\n\033[1;35mA I D A R   M 1 4 . 7   E 2 E   D E M O S T R A T I O N\033[0m\n")
        
        try:
            self.check_health()
            workers = self.list_workers()
            job_id = self.submit_job()
            self.monitor_job(job_id)
            self.verify_job(job_id)
            print("\n\033[1;32m=== DEMO SUCCESSFULLY COMPLETED ===\033[0m\n")
        except Exception as e:
            self._print_error(f"Demo failed: {e}")
            sys.exit(1)

    def check_health(self):
        self._print_step("1. Checking Coordinator Health")
        try:
            resp = httpx.get(f"{self.url}/api/v1/ping", timeout=5.0)
            resp.raise_for_status()
            self._print_success(f"Coordinator is reachable at {self.url}")
        except Exception as e:
            raise RuntimeError(f"Coordinator health check failed: {e}")

    def list_workers(self) -> List[Dict[str, Any]]:
        self._print_step("2. Querying Cluster Capacity")
        resp = httpx.get(f"{self.url}/api/v1/workers", headers=self.headers, timeout=5.0)
        
        if resp.status_code != 200:
            raise RuntimeError(f"Failed to query workers: HTTP {resp.status_code} - {resp.text}")
            
        workers = resp.json()
        active_workers = [w for w in workers if w.get("status") == "active"]
        
        if not active_workers:
            raise RuntimeError("No active workers found in the cluster. Demonstration requires at least 2.")
            
        self._print_success(f"Found {len(active_workers)} active worker nodes:")
        for w in active_workers:
            ram_str = "Unknown"
            if w.get('resource_profile') and w['resource_profile'].get('ram_total_bytes'):
                ram_str = f"{w['resource_profile']['ram_total_bytes'] / (1024**3):.1f} GB"
            self._print_info(f"Node: {w['worker_id']} (IP: {w['ip_address']}) - RAM: {ram_str} - Available CAS Capacity: {w.get('capacity_bytes', 0) / (1024**3):.1f} GB")
            
        if len(active_workers) < 2:
            raise RuntimeError("The demo requires at least 2 active workers to demonstrate multi-node distribution.")
            
        return active_workers

    def submit_job(self) -> str:
        self._print_step("3. Submitting Distributed Job")
        job_id = f"demo-job-{uuid.uuid4().hex[:8]}"
        
        # We will submit a 3-chunk job. 
        # The chunks must be distributed across different workers to prove M14.3.
        # Chunk 0 will generate a physical artifact.
        specs = []
        for i in range(3):
            cmd = f"python -c \"import time; time.sleep(3); print('chunk-{i}-success')\""
            if i == 0:
                cmd = f"python -c \"import time; import os; os.makedirs('outputs', exist_ok=True); open('outputs/artifact.txt', 'w').write('generated by chunk-0'); time.sleep(3); print('chunk-{i}-success')\""

            spec = {
                "workload_id": f"{job_id}-chunk-{i}",
                "job_id": job_id,
                "task_type": "test",
                "min_ram_bytes": 1024,
                "affinity_group_id": job_id,
                "affinity_mode": "different_worker",
                "affinity_hard": True,
                "parameters": {
                    "command": cmd
                }
            }
            specs.append(spec)
            
        payload = {"specs": specs}
        resp = httpx.post(f"{self.url}/api/v1/jobs/submit", json=payload, headers=self.headers, timeout=5.0)
        
        if resp.status_code != 202:
            raise RuntimeError(f"Job submission failed: HTTP {resp.status_code} - {resp.text}")
            
        self._print_success(f"Job {job_id} submitted with {len(specs)} workloads.")
        return job_id

    def monitor_job(self, job_id: str):
        self._print_step("4. Monitoring Execution & Placement")
        
        start_time = time.time()
        completed = False
        
        # State tracking
        workload_state = {}
        
        while time.time() - start_time < self.timeout:
            resp = httpx.get(f"{self.url}/api/v1/jobs/{job_id}", headers=self.headers, timeout=5.0)
            if resp.status_code != 200:
                self._print_error(f"Failed to query job state: {resp.status_code}")
                time.sleep(2)
                continue
                
            job_data = resp.json()
            workload_ids = job_data.get("workload_ids", [])
            
            # Print state summary
            self._print_info(f"Job {job_id} State: {job_data.get('state')} "
                             f"(Pending: {job_data.get('pending', 0)}, "
                             f"Running: {job_data.get('running', 0)}, "
                             f"Completed: {job_data.get('completed', 0)})")
                             
            # Print worker assignments if transitioned
            for wid in workload_ids:
                w_resp = httpx.get(f"{self.url}/api/v1/workloads/{wid}", headers=self.headers, timeout=5.0)
                if w_resp.status_code == 200:
                    w_data = w_resp.json()
                    state = w_data.get("state")
                    prev_state = workload_state.get(wid, {}).get("state")
                    
                    if state != prev_state:
                        if state in ["placed", "running"]:
                            placement = w_data.get("placement", {})
                            worker_id = placement.get("selected_worker_id", "unknown")
                            self._print_info(f"  -> Workload {wid} placed on worker {worker_id}")
                            
                        elif state == "completed":
                            attempts = w_data.get("attempts", [])
                            last_attempt = attempts[-1] if attempts else {}
                            self._print_success(f"  -> Workload {wid} completed successfully (Attempt {last_attempt.get('attempt_id', 'unknown')})")
                            
                        elif state == "failed":
                            self._print_error(f"  -> Workload {wid} failed!")
                            
                        workload_state[wid] = {"state": state, "data": w_data}
            
            if job_data.get("state") == "completed":
                completed = True
                break
                
            if job_data.get("state") == "failed":
                raise RuntimeError(f"Job failed during execution: {job_data}")
                
            time.sleep(2.0)
            print("\033[A\033[A\033[2K\r", end="") # Clear the job state line
            
        if not completed:
            raise RuntimeError(f"Demo timed out after {self.timeout} seconds waiting for job to complete.")

    def verify_job(self, job_id: str):
        self._print_step("5. Final Verification & Artifact Collection")
        
        resp = httpx.get(f"{self.url}/api/v1/jobs/{job_id}", headers=self.headers, timeout=5.0)
        job_data = resp.json()
        
        if job_data.get("state") != "completed":
            raise RuntimeError("Job is not in completed state.")
            
        workloads_run = []
        assigned_workers = set()
        
        for wid in job_data.get("workload_ids", []):
            w_resp = httpx.get(f"{self.url}/api/v1/workloads/{wid}", headers=self.headers)
            w_data = w_resp.json()
            workloads_run.append(w_data)
            
            placement = w_data.get("placement", {})
            if placement and "selected_worker_id" in placement:
                assigned_workers.add(placement["selected_worker_id"])
                
        self._print_success(f"Verified all {len(workloads_run)} workloads completed with Success=True")
        self._print_success(f"Verified Distributed Execution: workloads were successfully distributed across {len(assigned_workers)} distinct workers")
        
        if len(assigned_workers) < 2:
            self._print_error("Failed to demonstrate true multi-worker execution (all chunks ran on 1 worker).")
            raise RuntimeError("Distribution validation failed.")
            
        artifacts = job_data.get("output_asset_hashes", [])
        if artifacts:
            self._print_success(f"Discovered and indexed {len(artifacts)} CAS artifact(s) generated by the workloads:")
            for artifact_hash in artifacts:
                self._print_info(f"  - Hash: {artifact_hash}")
        else:
            self._print_error("No artifacts were aggregated to the final job state.")
            raise RuntimeError("Artifact tracking validation failed.")


def main():
    parser = argparse.ArgumentParser(description="AIDAR End-to-End M14.7 Demonstration")
    parser.add_argument("--url", type=str, default=os.environ.get("AIDAR_COORDINATOR_URL", "http://127.0.0.1:8000"),
                        help="Coordinator base URL (default: http://127.0.0.1:8000)")
    parser.add_argument("--token", type=str, default=os.environ.get("AIDAR_ADMIN_TOKENS", "test_token"),
                        help="Admin authorization token")
    parser.add_argument("--timeout", type=float, default=60.0,
                        help="Maximum time to wait for completion in seconds")
                        
    args = parser.parse_args()
    
    demo = AIDARDemo(url=args.url, token=args.token, timeout=args.timeout)
    demo.run()

if __name__ == "__main__":
    main()
